name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

variables:
  - template: variables/msbuild.yml
  - template: variables/vs2019.yml

trigger:
  batch: true
  branches:
    include:
      - master
      - "*-stable"

pr: none

jobs:
  - job: RnwNpmPublish
    displayName: React-Native-Windows Npm Build Rev Publish
    pool:
      vmImage: $(VmImage)
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 5
    steps:
      - checkout: self
        clean: true
        submodules: false
        persistCredentials: true

      - template: templates/configure-git.yml

      - task: CmdLine@2
        displayName: yarn install
        inputs:
          script: yarn install --frozen-lockfile

      - task: CmdLine@2
        displayName: yarn build
        inputs:
          script: yarn build

      - task: CmdLine@2
        displayName: Beachball Publish
        inputs:
          script: npx --no-install beachball publish --branch origin/$(Build.SourceBranchName) -n $(npmAuthToken) -yes -m "applying package updates ***NO_CI***" --bump-deps  --access public

      - task: CmdLine@2
        displayName: Set Version Env Vars
        name: setVersionEnvVars
        inputs:
          script: node ./.ado/setVersionEnvVars.js
        env:
          RUNNER_TEMP: $(Build.StagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: Publish VersionEnvVars
        inputs:
          PathtoPublish: $(Build.StagingDirectory)/versionEnvVars
          ArtifactName: VersionEnvVars

  - job: RnwNativeBuildDesktop
    displayName: Build Desktop
    dependsOn: RnwNpmPublish
    strategy:
      matrix:
        X64Debug:
          BuildConfiguration: Debug
          BuildPlatform: x64
        X86Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
        X64Release:
          BuildConfiguration: Release
          BuildPlatform: x64
        X86Release:
          BuildConfiguration: Release
          BuildPlatform: x86
    pool:
      vmImage: $(VmImage)

    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download VersionEnvVars
        inputs:
          artifactName: VersionEnvVars
          downloadPath: $(Build.StagingDirectory)

      - task: CmdLine@2
        inputs:
          script: node $(Build.StagingDirectory)/versionEnvVars/versionEnvVars.js

      - template: templates/build-rnw.yml
        parameters:
          project: vnext/ReactWindows-Desktop.sln
          msbuildArguments:
            /p:RNW_PKG_VERSION_STR="$(RNW_PKG_VERSION_STR)"
            /p:RNW_PKG_VERSION_MAJOR="$(RNW_PKG_VERSION_MAJOR)"
            /p:RNW_PKG_VERSION_MINOR="$(RNW_PKG_VERSION_MINOR)"
            /p:RNW_PKG_VERSION_PATCH="$(RNW_PKG_VERSION_PATCH)"

      - template: templates/publish-build-artifacts-for-nuget.yml
        parameters:
          artifactName: ReactWindows
          contents: |
            React.Windows.Desktop.DLL\**
            React.Windows.Desktop.Test.DLL\**

  - job: RnwNativeBuildUniversal
    displayName: Build Universal
    dependsOn: RnwNpmPublish
    strategy:
      matrix:
        X64Debug:
          BuildConfiguration: Debug
          BuildPlatform: x64
          LayoutHeaders: true
        X86Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
        ArmDebug:
          BuildConfiguration: Debug
          BuildPlatform: arm
        Arm64Debug:
          BuildConfiguration: Debug
          BuildPlatform: arm64
        X64Release:
          BuildConfiguration: Release
          BuildPlatform: x64
        X86Release:
          BuildConfiguration: Release
          BuildPlatform: x86
        ArmRelease:
          BuildConfiguration: Release
          BuildPlatform: arm
        Arm64Release:
          BuildConfiguration: Release
          BuildPlatform: arm64
    pool:
      vmImage: $(VmImage)

    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download VersionEnvVars
        inputs:
          artifactName: VersionEnvVars
          downloadPath: $(Build.StagingDirectory)

      - task: CmdLine@2
        inputs:
          script: node $(Build.StagingDirectory)/versionEnvVars/versionEnvVars.js

      - template: templates/build-rnw.yml
        parameters:
          project: vnext/ReactWindows-Universal.sln

      - template: templates/publish-build-artifacts-for-nuget.yml
        parameters:
          artifactName: ReactWindows
          layoutHeaders: eq('true', variables['LayoutHeaders'])
          contents: |
            ReactUWP\**
            Microsoft.ReactNative\**

    # Disable for now, not sure this works on github projects anyway.
    # - task: PublishSymbols@2
    #   displayName: 'Publish symbols path'
    #   inputs:
    #     SearchPattern: 'vnext/target/**/*.pdb'
    #     SymbolServerType: TeamServices
  - job: RNWNuget
    dependsOn:
      - RnwNpmPublish
      - RnwNativeBuildDesktop
      - RnwNativeBuildUniversal
    displayName: Publish Nuget
    pool:
      vmImage: $(VmImage)

    steps:
      - checkout: none

      - task: DownloadBuildArtifacts@0
        displayName: Download VersionEnvVars
        inputs:
          artifactName: VersionEnvVars
          downloadPath: $(Build.StagingDirectory)

      - task: CmdLine@2
        inputs:
          script: node $(Build.StagingDirectory)/VersionEnvVars/versionEnvVars.js

      # The commit tag in the nuspec requires that we use at least nuget 4.6
      - task: NuGetToolInstaller@0
        inputs:
          versionSpec: ">=4.6.0"

      - template: templates/prep-and-pack-nuget.yml
        parameters:
          publishCommitId: $(publishCommitId)
          npmVersion: $(npmVersion)

      - task: PublishBuildArtifacts@1
        displayName: "Publish final nuget artifacts"
        inputs:
          PathtoPublish: $(System.DefaultWorkingDirectory)\NugetRootFinal
          ArtifactName: "ReactWindows-final-nuget"
